### ISSUE TITLE
Segmentation fault when opening certain bigwig files

### ISSUE THREAD

**Issue by seisdrum** [dpryan79/pyBigWig#14]
Hey,

I have a couple of BigWig files that mysteriously lead to instant segfaults when I open them using pyBigWig. The one thing these files have in common, is that they are ChIP tracks aligned to the Drosophila r6.07 genome. Maybe there's a problem with some specific chromosome/scaffold names?

```
import pyBigWig
b = pyBigWig.open("problematic.bw")
```
Segmentation fault (core dumped)

They convert to bedgraph and back into bigwig using the UCSC tools just fine and I didn't notice any problems with them while browsing in IGV. I uploaded an example file at https://owncloud.gwdg.de/index.php/s/8u0dPjvSqqpQGkv

Thanks for your help!

**Comment by dpryan79** [comment]
Can you try the `fix14` branch? This should hopefully be fixed there. If that solves the problem I'll push out a new release today.

**Comment by seisdrum** [comment]
Yep, that solves the problem for me. Fantastic, thank you!
