### ISSUE TITLE
Installing on different directory

### ISSUE THREAD

**Issue by eranroz** [dpryan79/pyBigWig#21]
I'm trying to install pyBigWig with pip (python 3.5) on a different directory then the default one (I have no root access, and home directory has limited space)

It seems that the setup.py doesn't support neither --target nor --prefix. ( http://stackoverflow.com/questions/2915471/install-a-python-package-into-a-different-directory-using-pip )

```
 pip install --target=~/pysitePackages/ pyBigWig
 /usr/lib/python3/dist-packages/pip/commands/install.py:198: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
   cmdoptions.check_install_build_global(options)
 Collecting pyBigWig
   Using cached pyBigWig-0.2.8.tar.gz
 Skipping bdist_wheel for pyBigWig, due to binaries being disabled for it.
 Installing collected packages: pyBigWig
   Running setup.py install for pyBigWig ... error
     Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g8_x12wg/pyBigWig/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vz5xa_zy-record/install-record.txt --single-version-externally-managed --compile "\"--target=~/pysitePackages/\"" --user --prefix= --home=/tmp/tmpu3rg1ts8:
     /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'classifier'
       warnings.warn(msg)
     invalid command name '"--target=~/pysitePackages/"'
```
For now I work around it by installing it directly from source.

Thanks

**Comment by dpryan79** [comment]
$ mkdir foo
    $ pip3 install -t foo pyBigWig
    Collecting pyBigWig
      Downloading pyBigWig-0.2.8.tar.gz (49kB)
        100% |████████████████████████████████| 51kB 161kB/s 
    Building wheels for collected packages: pyBigWig
      Running setup.py bdist_wheel for pyBigWig ... done
      Stored in directory: /home/dpryan/.cache/pip/wheels/8b/53/0a/6bee3fbbb846daf59f8dcad82e7c2220b3749787403a6ce76d
    Successfully built pyBigWig
    Installing collected packages: pyBigWig
    Successfully installed pyBigWig-0.2.8

**Comment by dpryan79** [comment]
Since your python3 installation seems to have problems, you might find conda helpful.

**Comment by eranroz** [comment]
Thank you for the quick response. Solved (seems that the issue due to old pip [version 8.1.2] with some broken pip configurations)
