### ISSUE TITLE
Return location information when retrieve max value?

### ISSUE THREAD

**Issue by AlicePsyche** [dpryan79/pyBigWig#30]
Hi, 

Sorry, I think it is a simple question but I could not find it in documentation. Is it possible that I could retrieve the corresponding position when try to identify the max value of a region? 

```
bw.stats("chr1",72392,75996,type="max")
```

Thanks for your help!

**Comment by dpryan79** [comment]
The only way to do that in a bigwig file is to request the intervals and then iterate over them. Bigwigs store the max value in their zoom levels, otherwise I would have made what you want an option :)

**Comment by AlicePsyche** [comment]
😫  😢  Thanks anyway. 

It's a little embarrassing to ask here. Is it possible that you may recommend other tools can do this thing?  Actually I want the summits location of called peaks from ChIP-seq data. Just to plot heatmap around the summits(the most enriched signals could be aligned straightly). I know I can do what you said(request the intervals and then iterate over them) but it sounds not elegant enough... I have the bam file and peaks bed file. Is there no way to quickly spot where the most enriched signals locate? 

Thank you very much for your suggestions!

**Comment by dpryan79** [comment]
Perhaps your peak caller notes where the summit is. Otherwise there's no way around iterating over something.

**Comment by AlicePsyche** [comment]
Sorry for my ignorance... I intuitively thought there should be a easy way. Thanks for your help!
