### ISSUE TITLE
"Operation now in progress" error when loading remote bigWig files

### ISSUE THREAD

**Issue by pkerpedjiev** [dpryan79/pyBigWig#32]
I was trying to run the example in the README and got the following error:

	>>> import pyBigWig
	>>> bw = pyBigWig.open("http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeMapability/wgEncodeCrgMapabilityAlign75mer.bigWig")
	>>> bw.stats('chr1', 89294, 91629)
	got an error in bwStatsFromZoom in the range 89294-91629: Operation now in progress
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	RuntimeError: An error was encountered while fetching statistics.

I'm using python 2.7 on an Apple:

	>>> sys.version
	'2.7.11 (default, Nov 17 2016, 17:37:33) \n[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]'

**Comment by dpryan79** [comment]
I can reproduce this under Linux. I'm not exactly sure why libcurl is setting the EINPROGRESS error, since if I ignore it then everything works correctly. I'll have to have a look at this next week to see if I can find the root cause.

**Comment by dpryan79** [comment]
I've fixed this for the 0.3.5 release. For some unknown reason, libCurl sometimes is setting an into error and then resolving the issue without then removing that flag. I'm trying to removing it myself so it doesn't muck up this library.
