### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by sarinaddaf** [dpryan79/pyBigWig#33]
hello,

i'm new to python and trying to install this package. I already tried to install it through pip and through the pycharm gui.
i get this error:

> Collecting pyBigWig
>   Using cached pyBigWig-0.3.4.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\sarin\AppData\Local\Temp\pycharm-packaging\pyBigWig\setup.py", line 21, in <module>
>         for e in sysconfig.get_config_vars('BLDLIBRARY')[0].split():
>     AttributeError: 'NoneType' object has no attribute 'split'
>     
>     ----------------------------------------
> 
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\sarin\AppData\Local\Temp\pycharm-packaging\pyBigWig\
> 

is there something im missing? and how could i fix this issue?

thanks allot in advance

**Comment by dpryan79** [comment]
You're the first person to ever try this on windows :) I can program around that particular windows-specific error, but I really don't know if things will generally work there. I'll try to borrow a windows computer and check.

**Comment by dpryan79** [comment]
Do you have Visual C++ installed? That will be needed to install this on Windows. In general, a lot of things won't work on Windows or, if they do, they'll be really hard for you to install. I'd really recommend borrowing a Mac or getting Linux installed on a dual-boot system.

**Comment by idostyle** [comment]
There same error happens on a linux system when installing from pip using pypy:

```
$ pip install pyBigWig
Collecting pyBigWig
  Using cached https://files.pythonhosted.org/packages/d5/0d/8e2a1edb9524790c6a4d0b70bc800a8e4afee1bc7bdd048c54b8d9cf1c32/pyBigWig-0.3.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<module>", line 1, in <module>
      File "/tmp/pip-install-Tff8kf/pyBigWig/setup.py", line 24, in <module>
        for e in sysconfig.get_config_vars('BLDLIBRARY')[0].split():
    AttributeError: 'NoneType' object has no attribute 'split'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Tff8kf/pyBigWig/
```

```
Linux linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
```

```
Python 2.7.13 (ab0b9caf307db6592905a80b8faffd69b39005b8, Apr 30 2018, 08:21:35)
[PyPy 6.0.0 with GCC 7.2.0] on linux2
```

**Comment by dpryan79** [comment]
pypy does not support modules like pyBigWig, you'll need to use regular python.
