### ISSUE TITLE
Allow pyBigWig.open() in with statement.

### ISSUE THREAD

**Issue by ghuls** [dpryan79/pyBigWig#35]
It would be nice if pyBigWig.open() could be used with the **with** statement:
```python
with pyBigWig.open('ENCFF001LFU.broadPeak.bigbed', 'rb') as bb:
    print(bb.header())
```

It is missing \_\_exit\_\_ and \_\_enter\_\_ methods.

**Comment by dpryan79** [comment]
Thanks, I'll try to have a look at your PR today. I'm not a fan of using `with`, so I guess I never noticed that it uses those methods.

**Comment by ghuls** [comment]
Thanks. At least the first patch on that branch solves a real bug in pyBigWig, so if at least that one can be merged, I am already happy.

**Comment by dpryan79** [comment]
I've just taken care of this with #41, thanks!
