### ISSUE TITLE
undefined symbol: hasEntries

### ISSUE THREAD

**Issue by seisdrum** [dpryan79/pyBigWig#45]
Using version 0.3.5 I'm getting this error when importing pyBigWig (Python 2.7.9 on Ubuntu 15.04):

`ImportError: /home/chug/kaic_venv/local/lib/python2.7/site-packages/pyBigWig.so: undefined symbol: hasEntries`

I installed it using the binary wheel from PyPI. The symbol hasEntries doesn't seem to be properly exported: 

```
> readelf -a /home/chug/kaic_venv/local/lib/python2.7/site-packages/pyBigWig.so | grep hasEntries
000000216038  000600000007 R_X86_64_JUMP_SLO 0000000000000000 hasEntries + 0
      6: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND hasEntries
    100: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND hasEntries
```

Interestingly, when I install from source using `pip install  --no-binary :all: pyBigWig` it works fine.

**Comment by dpryan79** [comment]
Sorry about this and the delayed reply. I'm posting a new version now with this fixed. The problem was due to the `hasEntries()` function being in an `ifdef` that's only used if numpy is present upon compilation. That was an accident on my part.

**Comment by dpryan79** [comment]
Version 0.3.6 is now available via `pip install` and should have this fixed.

**Comment by seisdrum** [comment]
Works great, thank you very much!
