### ISSUE TITLE
RuntimeError: Invalid interval bounds!

### ISSUE THREAD

**Issue by bhchiang** [dpryan79/pyBigWig#49]
Running  dnasevals=np.array(self.bw.values(chrm,start,end))
with this
chrm=chr2
start=242396100,end=242397100

on this file: https://www.encodeproject.org/files/ENCFF743ULW/@@download/ENCFF743ULW.bigWig (download)

Getting error "RuntimeError: Invalid interval bounds!"

According to hg19 genome length of chr2 is 243199373.

Is this an issue with the Dnase-seq file? How can I check size of chrom with pyBigWig? Thanks so much!

**Comment by dpryan79** [comment]
> import pyBigWig
    > bw = pyBigWig.open("https://www.encodeproject.org/files/ENCFF743ULW/@@download/ENCFF743ULW.bigWig")
    > bw.chroms("chr2")
    242193529L

So that's why you get the error and how you can check chromosome sizes.

**Comment by bhchiang** [comment]
Thanks, the DNase-seq file I was using was mapped against hg38 (chr2 length=242193529) , but the intervals were derived from hg19 (chr2 length=243199373).

**Comment by shamsbhuiyan** [comment]
Hello, I am hit with a similar issue. However, I am using the same build and I've double checked the length of chromosome 6.
```
Traceback (most recent call last):
  File "find_sORFs.py", line 245, in <module>
    compute_phylop_score("five_prime_sORFs.bed",human_phylop_bigwig)
  File "find_sORFs.py", line 222, in compute_phylop_score
    vals = bw.values(cols[0], int(cols[1]), int(cols[2]))
RuntimeError: Invalid interval bounds!
```

This breaks at 'chr6', '83707928', '83707957', but the length of chromosome 6 according `bw.chroms("chr6")` is 170805979

**Comment by Jome0169** [comment]
Hi @shamsbhuiyan did you ever figure this out? Getting the same error and can't figure out what might be causing it.
