### ISSUE TITLE
Command 'clang' failed with exit status 1

### ISSUE THREAD

**Issue by cguzman92** [dpryan79/pyBigWig#5]
I am attempting to use your 1.6 release version of deepTools, but I run into a problem when attempting to install pyBigWig through pip or by cloning the git repository locally.

I am getting the following error: `error: command 'clang' failed with exit status 1`
And during the pip install I recieve a similar error with a "Cannot build wheel for pyBigWig" error.

I've searched but can't seem to find a way to fix this. I am using an iMAC OSX El Capitan version 10.11.2. I have the most recent pip installation and setuptools is installed as well as the latest Xcode and command line tools. My clang version is `Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix`

Thanks,

**Comment by dpryan79** [comment]
Weird, I'll have to test this on an OSX system after the holidays. The last time I tried this on a Mac it worked, but perhaps I've inadvertently broken that :(

Do you get any more output than that (e.g., the lines starting with clang)? That'd help me at least nail down where things are breaking.

**Comment by cguzman92** [comment]
I'll include them here, if you'd prefer a txt file of the entire error log I can send that to you through e-mail as well.

```
clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -IlibBigWig -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c libBigWig/bwRead.c -o build/temp.macosx-10.11-x86_64-2.7/libBigWig/bwRead.o
  clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -IlibBigWig -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c libBigWig/bwStats.c -o build/temp.macosx-10.11-x86_64-2.7/libBigWig/bwStats.o
  clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -IlibBigWig -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c libBigWig/bwValues.c -o build/temp.macosx-10.11-x86_64-2.7/libBigWig/bwValues.o
  clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -IlibBigWig -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c libBigWig/io.c -o build/temp.macosx-10.11-x86_64-2.7/libBigWig/io.o
  clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -IlibBigWig -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pyBigWig.c -o build/temp.macosx-10.11-x86_64-2.7/pyBigWig.o
  pyBigWig.c:289:30: error: void function 'initpyBigWig' should not return a value [-Wreturn-type]
      if(Py_AtExit(bwCleanup)) return NULL;
                               ^      ~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1
```

**Comment by dpryan79** [comment]
I hopefully just fixed that. Can you try the following:
`pip install --user git+https://github.com/dpryan79/pyBigWig.git`

**Comment by cguzman92** [comment]
Yep that fixed it! Thanks a lot.

**Comment by dpryan79** [comment]
Great, it was thankfully an easy fix.
