### ISSUE TITLE
problem with installing pyBigWig

### ISSUE THREAD

**Issue by simjbaum** [dpryan79/pyBigWig#9]
Hello, 
I tried to install pyBigWig on linux in order to use deeptools 2, unfortunately I get these errors: 

Linux distribution I am using
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

python I am using 
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

##### I am unsure here what more information I should provide ######

The errors:  #1

simon@simon-Aspire-E1-572:~$ sudo -H pip install git+git://github.com/dpryan79/pyBigWig.git
Collecting git+git://github.com/dpryan79/pyBigWig.git
  Cloning git://github.com/dpryan79/pyBigWig.git to /tmp/pip-9zWXyi-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-9zWXyi-build/setup.py", line 24, in <module>
        foo, _ = subprocess.Popen(['curl-config', '--libs'], stdout=subprocess.PIPE).communicate()
      File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-9zWXyi-build

############

Error #2 

When I am trying to install it "directly" in the folder where I downloaded it, I get this error:

simon@simon-Aspire-E1-572:~/Downloads/pyBigWig-0.2.3$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    foo, _ = subprocess.Popen(['curl-config', '--libs'], stdout=subprocess.PIPE).communicate()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Any help is very much appreciated. This is actually my first "help" post. If you need more information or have suggestions how I can improve my question I am very open for suggestions. 

Best wishes,
Simon

**Comment by dpryan79** [comment]
You don't have libcurl installed. `sudo apt-get install libcurl4-openssl-dev`. BTW, I would strongly discourage you from using sudo with pip. A simple `pip install pyBigWig --user` (or `pip install . --user` from within the directory with the source code) will work.

**Comment by simjbaum** [comment]
Thank you for your fast answer. It worked. I do not want to spam, but I am curious how you saw that I have not installed libcurl?

**Comment by dpryan79** [comment]
It was in the error message :)

OK, not really, but that error message will only occur if libcurl isn't installed (because it comes with `curl-config` and the lack of that caused the error). I should make it print a nice error message rather than python dying.
